global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "api-monitoring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-monitoring:8080"]